name: Build MTBWise App

on: push

permissions:
  contents: write

jobs:
  icons:
    name: Build Icons
    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ImageMagick
        run: brew install imagemagick

      - name: Build icons
        run: ./icon-make.sh

      - name: Upload build icons
        uses: actions/upload-artifact@v4
        with:
          name: build-icons
          path: build/**
          if-no-files-found: error

  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    needs: icons
    strategy:
      fail-fast: false
      matrix:
        os: [macos-26]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Download build icons
        uses: actions/download-artifact@v4
        with:
          name: build-icons
          path: build

      - name: Build (Windows)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: matrix.os == 'windows-latest'
        run: yarn dist:win

      - name: Build (macOS)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: matrix.os == 'macos-26'
        run: yarn dist:mac
